import React from "react";
import { Document, Page, Text, View, StyleSheet, Font, renderToBuffer } from "@react-pdf/renderer";

Font.register({
  family: "Noto Sans Bengali",
  fonts: [
    { src: "https://fonts.gstatic.com/s/notosansbengali/v28/7g8TVUY_wEhJwH9eF4dU7n3gHO6o0B0.woff2" },
  ],
});

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Noto Sans Bengali", fontSize: 10 },
  header: { marginBottom: 20, textAlign: "center" },
  title: { fontSize: 16, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#555", marginBottom: 4 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: 700, borderBottom: "1 solid #333", paddingBottom: 4, marginBottom: 8 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: "40%", fontSize: 10, color: "#444" },
  value: { width: "60%", fontSize: 10 },
  table: { marginTop: 8 },
  tableHeader: { flexDirection: "row", backgroundColor: "#f0f0f0", borderBottom: "1 solid #333" },
  tableRow: { flexDirection: "row", borderBottom: "1 solid #ddd" },
  tableCell: { padding: 4, fontSize: 9, flex: 1 },
  tableCellHeader: { padding: 4, fontSize: 9, flex: 1, fontWeight: 700 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#999", borderTop: "1 solid #ddd", paddingTop: 8 },
  watermark: { position: "absolute", top: "40%", left: 0, right: 0, textAlign: "center", fontSize: 48, color: "#ddd", transform: "rotate(-30deg)" },
});

interface PDFFormData {
  titleBn: string;
  titleEn: string;
  formId: string;
  sections: { title: string; fields: { label: string; value: string }[] }[];
  status: string;
}

function flattenFormData(formData: Record<string, unknown>, schema: any): PDFFormData["sections"] {
  if (!schema?.sections) return [];
  return schema.sections.map((sec: any) => ({
    title: sec.titleBn,
    fields: sec.fields.map((f: any) => {
      // Handle array fields
      if (f.type === "array") {
        const items = (formData[f.id] as any[]) || [];
        return {
          label: f.labelBn,
          value: items.length > 0
            ? items.map((item, i) =>
                f.fields
                  ? f.fields.map((sf: any) => `${sf.labelBn}: ${item[sf.id] ?? ""}`).join(", ")
                  : JSON.stringify(item)
              ).join("\n")
            : "-",
        };
      }
      const val = formData[f.id];
      return {
        label: f.labelBn,
        value: val != null ? String(val) : "-",
      };
    }),
  }));
}

export function generateFormPDF(
  formId: string,
  formData: Record<string, unknown>,
  definition: { titleBn: string; titleEn: string },
  schema: any
) {
  const sections = flattenFormData(formData, schema);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{definition.titleBn}</Text>
          <Text style={styles.subtitle}>{definition.titleEn} ({formId})</Text>
          <Text style={styles.subtitle}>জাতীয় রাজস্ব বোর্ড — ভ্যাট অনলাইন সিস্টেম</Text>
        </View>

        {sections.map((section, si) => (
          <View key={si} style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            {section.fields.map((field, fi) => (
              field.value.includes("\n") ? (
                <View key={fi} style={{ marginBottom: 6 }}>
                  <Text style={[styles.label, { width: "100%", marginBottom: 2 }]}>{field.label}</Text>
                  {field.value.split("\n").map((line, li) => (
                    <Text key={li} style={[styles.value, { width: "100%", paddingLeft: 8, marginBottom: 1 }]}>• {line}</Text>
                  ))}
                </View>
              ) : (
                <View key={fi} style={styles.row}>
                  <Text style={styles.label}>{field.label}</Text>
                  <Text style={styles.value}>{field.value}</Text>
                </View>
              )
            ))}
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by TaxFlow — ভ্যাট ও কমপ্লায়েন্স সহায়ক | {new Date().toLocaleDateString("bn-BD")}
        </Text>
      </Page>
    </Document>
  );
}

export async function pdfToBuffer(element: unknown): Promise<Uint8Array> {
  const buf = await renderToBuffer(element as any);
  return new Uint8Array(buf);
}
